apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    tier: frontend
  template:
    metadata:
      name: nginx-pod
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
           - containerPort: 80

